#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &
bspc monitor -d I II III IV V

bspc config border_width 1
bspc config window_gap 10

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config focus_follows_pointer true
bspc config active_border_color "#282828"
bspc config focused_border_color "#1d2021"

bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled

$HOME/.config/bspwm/autostart &
